import { DanceRoutine, YouTubeVideoInfo } from "./types";

export const PREBUILT_ROUTINES: DanceRoutine[] = [
  {
    songTitle: "Thriller",
    artist: "Michael Jackson",
    genre: "Pop / Disco",
    tempoBpm: 118,
    difficulty: "Intermediate",
    styleDescription: "The iconic retro Halloween zombie walk with staggered offsets, side clicks, and dynamic hip tilts.",
    steps: [
      {
        stepNumber: 1,
        name: "Zombie Crouch Wakeup",
        description: "Stand with knees bent and hunched forward, hands dangling downwards like emerging from a tomb.",
        beats: "Beats 1-2",
        head: { x: 50, y: 28 },
        neck: { x: 50, y: 38 },
        pelvis: { x: 50, y: 72 },
        leftShoulder: { x: 42, y: 40 },
        rightShoulder: { x: 58, y: 40 },
        leftElbow: { x: 38, y: 56 },
        leftHand: { x: 34, y: 72 },
        rightElbow: { x: 62, y: 56 },
        rightHand: { x: 66, y: 72 },
        leftHip: { x: 45, y: 72 },
        rightHip: { x: 55, y: 72 },
        leftKnee: { x: 40, y: 92 },
        leftFoot: { x: 36, y: 110 },
        rightKnee: { x: 60, y: 92 },
        rightFoot: { x: 64, y: 110 },
        faceExpression: "neutral"
      },
      {
        stepNumber: 2,
        name: "Zombie Left Slide",
        description: "Reach both arms out to the left, head tilting sideways, sliding left foot outwards.",
        beats: "Beats 3-4",
        head: { x: 46, y: 23 },
        neck: { x: 48, y: 32 },
        pelvis: { x: 55, y: 68 },
        leftShoulder: { x: 38, y: 32 },
        rightShoulder: { x: 58, y: 34 },
        leftElbow: { x: 26, y: 30 },
        leftHand: { x: 14, y: 28 },
        rightElbow: { x: 42, y: 36 },
        rightHand: { x: 28, y: 34 },
        leftHip: { x: 50, y: 68 },
        rightHip: { x: 60, y: 68 },
        leftKnee: { x: 36, y: 88 },
        leftFoot: { x: 24, y: 110 },
        rightKnee: { x: 60, y: 88 },
        rightFoot: { x: 60, y: 110 },
        faceExpression: "focus"
      },
      {
        stepNumber: 3,
        name: "Zombie Right Chest Pop",
        description: "Slam hands back to the right, lifting your torso high to express pop impact.",
        beats: "Beats 5-6",
        head: { x: 54, y: 20 },
        neck: { x: 52, y: 30 },
        pelvis: { x: 45, y: 68 },
        leftShoulder: { x: 42, y: 34 },
        rightShoulder: { x: 62, y: 32 },
        leftElbow: { x: 58, y: 36 },
        leftHand: { x: 72, y: 34 },
        rightElbow: { x: 74, y: 30 },
        rightHand: { x: 86, y: 28 },
        leftHip: { x: 40, y: 68 },
        rightHip: { x: 50, y: 68 },
        leftKnee: { x: 40, y: 88 },
        leftFoot: { x: 40, y: 110 },
        rightKnee: { x: 64, y: 88 },
        rightFoot: { x: 76, y: 110 },
        faceExpression: "excited"
      },
      {
        stepNumber: 4,
        name: "The Famous Head Snap",
        description: "Snap your head sharply to the front with shoulders locked and hands held like terrifying claws.",
        beats: "Beats 7-8",
        head: { x: 50, y: 24 },
        neck: { x: 50, y: 34 },
        pelvis: { x: 50, y: 68 },
        leftShoulder: { x: 38, y: 36 },
        rightShoulder: { x: 62, y: 36 },
        leftElbow: { x: 28, y: 48 },
        leftHand: { x: 22, y: 38 },
        rightElbow: { x: 72, y: 48 },
        rightHand: { x: 78, y: 38 },
        leftHip: { x: 44, y: 68 },
        rightHip: { x: 56, y: 68 },
        leftKnee: { x: 40, y: 88 },
        leftFoot: { x: 35, y: 110 },
        rightKnee: { x: 60, y: 88 },
        rightFoot: { x: 65, y: 110 },
        faceExpression: "cool"
      }
    ]
  },
  {
    songTitle: "Gangnam Style",
    artist: "Psy",
    genre: "K-Pop",
    tempoBpm: 132,
    difficulty: "Beginner",
    styleDescription: "The energetic horse-riding dance combining hand crossing, gallop-bounces, and dynamic lasso spins.",
    steps: [
      {
        stepNumber: 1,
        name: "Cross Wrists Riding",
        description: "Cross your wrists in front of your chest and bounce slightly with legs wide.",
        beats: "Beat 1",
        head: { x: 50, y: 26 },
        neck: { x: 50, y: 36 },
        pelvis: { x: 50, y: 72 },
        leftShoulder: { x: 40, y: 38 },
        rightShoulder: { x: 60, y: 38 },
        leftElbow: { x: 48, y: 48 },
        leftHand: { x: 52, y: 48 },
        rightElbow: { x: 52, y: 48 },
        rightHand: { x: 48, y: 48 },
        leftHip: { x: 44, y: 72 },
        rightHip: { x: 56, y: 72 },
        leftKnee: { x: 32, y: 90 },
        leftFoot: { x: 28, y: 110 },
        rightKnee: { x: 68, y: 90 },
        rightFoot: { x: 72, y: 110 },
        faceExpression: "smile"
      },
      {
        stepNumber: 2,
        name: "Horse Gallop Rise",
        description: "Raise your body up on your toes, holding your crossed hands firmly in place.",
        beats: "Beat 2",
        head: { x: 50, y: 18 },
        neck: { x: 50, y: 28 },
        pelvis: { x: 50, y: 64 },
        leftShoulder: { x: 40, y: 30 },
        rightShoulder: { x: 60, y: 30 },
        leftElbow: { x: 48, y: 40 },
        leftHand: { x: 52, y: 40 },
        rightElbow: { x: 52, y: 40 },
        rightHand: { x: 48, y: 40 },
        leftHip: { x: 44, y: 64 },
        rightHip: { x: 56, y: 64 },
        leftKnee: { x: 42, y: 84 },
        leftFoot: { x: 40, y: 104 },
        rightKnee: { x: 58, y: 84 },
        rightFoot: { x: 60, y: 104 },
        faceExpression: "excited"
      },
      {
        stepNumber: 3,
        name: "Right Hand Lasso Spin",
        description: "Hold your left hand steady in front of you, while swinging your right hand in a circular lasso above your head.",
        beats: "Beat 3",
        head: { x: 50, y: 24 },
        neck: { x: 50, y: 34 },
        pelvis: { x: 50, y: 70 },
        leftShoulder: { x: 40, y: 36 },
        rightShoulder: { x: 60, y: 36 },
        leftElbow: { x: 32, y: 48 },
        leftHand: { x: 34, y: 56 },
        rightElbow: { x: 74, y: 24 },
        rightHand: { x: 68, y: 10 },
        leftHip: { x: 44, y: 70 },
        rightHip: { x: 56, y: 70 },
        leftKnee: { x: 36, y: 90 },
        leftFoot: { x: 32, y: 110 },
        rightKnee: { x: 64, y: 90 },
        rightFoot: { x: 68, y: 110 },
        faceExpression: "cool"
      },
      {
        stepNumber: 4,
        name: "Gallop Lasso Accent",
        description: "Lean slightly to the right to match the spinning action.",
        beats: "Beat 4",
        head: { x: 54, y: 26 },
        neck: { x: 52, y: 36 },
        pelvis: { x: 48, y: 72 },
        leftShoulder: { x: 42, y: 38 },
        rightShoulder: { x: 62, y: 36 },
        leftElbow: { x: 34, y: 50 },
        leftHand: { x: 36, y: 58 },
        rightElbow: { x: 78, y: 22 },
        rightHand: { x: 86, y: 14 },
        leftHip: { x: 42, y: 72 },
        rightHip: { x: 54, y: 72 },
        leftKnee: { x: 36, y: 92 },
        leftFoot: { x: 32, y: 110 },
        rightKnee: { x: 60, y: 92 },
        rightFoot: { x: 64, y: 110 },
        faceExpression: "smile"
      }
    ]
  },
  {
    songTitle: "Billie Jean",
    artist: "Michael Jackson",
    genre: "Pop / Funk",
    tempoBpm: 120,
    difficulty: "Advanced",
    styleDescription: "Elegant street soul pop showing the classic right hand hat tilt and Left foot backward Moonwalk kick-stand.",
    steps: [
      {
        stepNumber: 1,
        name: "The Fedora Tilt",
        description: "Grab fedora brim with your right hand, left hand back on hip, leaning backwards on your left foot.",
        beats: "Beats 1-2",
        head: { x: 44, y: 24 },
        neck: { x: 46, y: 34 },
        pelvis: { x: 48, y: 70 },
        leftShoulder: { x: 38, y: 36 },
        rightShoulder: { x: 56, y: 34 },
        leftElbow: { x: 26, y: 48 },
        leftHand: { x: 30, y: 58 },
        rightElbow: { x: 60, y: 26 },
        rightHand: { x: 52, y: 16 },
        leftHip: { x: 44, y: 70 },
        rightHip: { x: 54, y: 70 },
        leftKnee: { x: 40, y: 90 },
        leftFoot: { x: 36, y: 110 },
        rightKnee: { x: 64, y: 90 },
        rightFoot: { x: 68, y: 110 },
        faceExpression: "cool"
      },
      {
        stepNumber: 2,
        name: "Pelvic Thrust Rock",
        description: "Pop hips aggressively forward, pointing left index finger out.",
        beats: "Beats 3-4",
        head: { x: 54, y: 22 },
        neck: { x: 50, y: 32 },
        pelvis: { x: 58, y: 68 },
        leftShoulder: { x: 42, y: 34 },
        rightShoulder: { x: 58, y: 34 },
        leftElbow: { x: 34, y: 36 },
        leftHand: { x: 18, y: 32 },
        rightElbow: { x: 68, y: 46 },
        rightHand: { x: 74, y: 58 },
        leftHip: { x: 52, y: 68 },
        rightHip: { x: 64, y: 68 },
        leftKnee: { x: 45, y: 88 },
        leftFoot: { x: 40, y: 108 },
        rightKnee: { x: 66, y: 88 },
        rightFoot: { x: 68, y: 110 },
        faceExpression: "focus"
      },
      {
        stepNumber: 3,
        name: "Moonwalk Foot Slide",
        description: "Raise left heel up high, press right foot flat against the floor and slide it smoothly backwards.",
        beats: "Beats 5-6",
        head: { x: 48, y: 20 },
        neck: { x: 48, y: 30 },
        pelvis: { x: 48, y: 66 },
        leftShoulder: { x: 38, y: 32 },
        rightShoulder: { x: 58, y: 32 },
        leftElbow: { x: 28, y: 44 },
        leftHand: { x: 22, y: 54 },
        rightElbow: { x: 68, y: 44 },
        rightHand: { x: 74, y: 54 },
        leftHip: { x: 42, y: 66 },
        rightHip: { x: 54, y: 66 },
        leftKnee: { x: 38, y: 86 },
        leftFoot: { x: 38, y: 102 },
        rightKnee: { x: 58, y: 86 },
        rightFoot: { x: 70, y: 110 },
        faceExpression: "neutral"
      },
      {
        stepNumber: 4,
        name: "The Famous Toe Stand",
        description: "Go up instantly onto the tips of your toes with fingers snapped wide in a burst of power.",
        beats: "Beats 7-8",
        head: { x: 50, y: 16 },
        neck: { x: 50, y: 26 },
        pelvis: { x: 50, y: 62 },
        leftShoulder: { x: 38, y: 28 },
        rightShoulder: { x: 62, y: 28 },
        leftElbow: { x: 24, y: 26 },
        leftHand: { x: 12, y: 20 },
        rightElbow: { x: 76, y: 26 },
        rightHand: { x: 88, y: 20 },
        leftHip: { x: 44, y: 62 },
        rightHip: { x: 56, y: 62 },
        leftKnee: { x: 42, y: 82 },
        leftFoot: { x: 40, y: 98 },
        rightKnee: { x: 58, y: 82 },
        rightFoot: { x: 60, y: 98 },
        faceExpression: "excited"
      }
    ]
  }
];

export const FALLBACK_YOUTUBE_VIDEOS: YouTubeVideoInfo[] = [
  {
    id: "sOnqjkJTMaA",
    title: "Michael Jackson - Thriller (Official Video)",
    description: "Michael Jackson's world-famous 14-minute music video, featuring the spectacular zombie dance choreography.",
    thumbnailUrl: "https://img.youtube.com/vi/sOnqjkJTMaA/0.jpg",
    channelTitle: "Michael Jackson",
    publishedAt: "2009-10-03",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-girl-dancing-hip-hop-in-the-street-40324-large.mp4"
  },
  {
    id: "9bZkp7q19f0",
    title: "PSY - GANGNAM STYLE(강남스타일) M/V",
    description: "The viral horse-riding dance phenomenon that captured the world with exciting gallops and lasso swings.",
    thumbnailUrl: "https://img.youtube.com/vi/9bZkp7q19f0/0.jpg",
    channelTitle: "officialpsy",
    publishedAt: "2012-07-15",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-dancer-performing-in-a-neon-lit-room-40327-large.mp4"
  },
  {
    id: "Zi_XLOBDo_Y",
    title: "Michael Jackson - Billie Jean (Official Video)",
    description: "The classic music video featuring the signature fedora hand grab and revolutionary dance movements.",
    thumbnailUrl: "https://img.youtube.com/vi/Zi_XLOBDo_Y/0.jpg",
    channelTitle: "Michael Jackson",
    publishedAt: "2009-10-03",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-man-dancing-under-neon-lights-40331-large.mp4"
  }
];
